### PR TITLE
Request issue labeler key in action

### PR DESCRIPTION
**Pull request by benbp**
Updates the event processor action to request the issue labeler service API key using a login from github OIDC auth.

Right now the claims are set up so the login will only work when the action is run from the main branch. I can broaden this scope for testing if needed.

TODO - I'm still experimenting with how to get an access token via OIDC for azure functions itself.

@JimSuplizio The function program example that you were using can be updated to use this new value like so:

```
// Change from this
const string FunctionAppKey = "<< JIM SHOULD ADD THE FUNCTION KEY HERE >>";
// To this
const string FunctionAppKey = System.Environment.GetEnvironmentVariable("LABEL_SERVICE_API_KEY");
```

### CODE REVIEW

**Review by JimSuplizio — APPROVED** [review]

**Comment by JimSuplizio** [comment]
@benbp, I think there's something going on with the az login.

**Comment by benbp** [comment]
> @benbp, I think there's something going on with the az login.

@JimSuplizio the identity is not authorized to access the labeler for pull requests, it can only login successfully from main

**Comment by JimSuplizio** [comment]
> @JimSuplizio the identity is not authorized to access the labeler for pull requests, it can only login successfully from main

@benbp, then we might want to do something where it doesn't try unless it's main so it's not logging a failure like it is here. That's going to end up being confusing and, most likely, going to be incorrectly blamed for things caused by other issues.

**Comment by benbp** [comment]
@JimSuplizio updated with short term handling for issue events only. The env lookup at the bottom works if not defined via the skipped steps (defaults to empty).

**Pull request merged**
